description: "A new Flutter application."
name: "ehatid_passenger_app"
publish_to: "none"
version: "1.0.0+1"
dependencies:
  cupertino_icons: "^1.0.5"
  intro_slider: ^2.3.4
  simple_animations: ^5.0.0+2
  animate_do: ^2.1.0
  intl_phone_number_input: ^0.7.0+2
  path_drawing: "^1.0.0"
  flutter:
    sdk: "flutter"
  supercharged: ^2.1.1
dev_dependencies:
  flutter_test:
    sdk: "flutter"
  flutter_lints: ^2.0.0
environment:
  sdk: ">=2.17.0 <3.0.0"
flutter:
  assets:
    - assets/images/
  fonts:
    -
      family: "Rubik"
      fonts:
        -
          asset: assets/fonts/Rubik-Regular.ttf
          style: "normal"
          weight: 400
    -
      family: "Montserrat"
      fonts:
        -
          asset: assets/fonts/Montserrat-Bold.ttf
          style: "normal"
          weight: 900
        -
          asset: assets/fonts/Montserrat-Regular.ttf
          style: "normal"
        -
          asset: assets/fonts/Montserrat-SemiBold.ttf
          style: "normal"
          weight: 500
        -
          asset: assets/fonts/Montserrat-Medium.ttf
          style: "normal"
          weight: 300
        -
          asset: assets/fonts/Montserrat-Regular.ttf
          style: "italic"
          weight: 500
  uses-material-design: true
